export const IITF_REFERENCE = {
  title: "IITF Pavilion Video Reference",
  subtitle: "Rajasthan Pavilion Design Research — Latest to Earliest",
  purpose:
    "Video reference list for IITF 2026 Rajasthan Pavilion research. Latest material is placed first; earlier years follow below. Direct video links are provided where verified, while year-specific YouTube searches are used where historical uploads could not be reliably verified.",
} as const;

export const IITF_REFERENCE_SECTIONS = [
  {
    heading: "IITF 2025 — Official & General",
    links: [
      { label: "IITF 2025 Official", url: "https://www.youtube.com/watch?v=vNMJzDdntAo&utm_source=chatgpt.com" },
      { label: "IITF 2025 Overview", url: "https://www.youtube.com/results?search_query=IITF+2025+full+walkthrough+pavilions&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "IITF 2024 — Official & General",
    links: [
      { label: "IITF 2024 Walkthrough", url: "https://www.youtube.com/watch?v=m59opzhXfMg&utm_source=chatgpt.com" },
      { label: "IITF 2024 Full Tour", url: "https://www.youtube.com/watch?v=AcgpTKF3woI&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "Rajasthan Pavilion — 2025 to 2013",
    links: [
      { label: "Rajasthan Pavilion 2025", url: "https://www.youtube.com/watch?v=WI_BRFpg400&utm_source=chatgpt.com" },
      { label: "Rajasthan 2025 Tour", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Rajasthan Gold 2025", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+Gold+IITF+2025&utm_source=chatgpt.com" },
      { label: "Rajasthan 2024", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2024&utm_source=chatgpt.com" },
      { label: "Rajasthan 2024 Walkthrough", url: "https://www.youtube.com/watch?v=m59opzhXfMg&t=2178s&utm_source=chatgpt.com" },
      { label: "Rajasthan Pavilion 2023", url: "https://www.youtube.com/watch?v=cMjWX35Vm7s&utm_source=chatgpt.com" },
      { label: "Rajasthan 2023 Tour", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2023+tour&utm_source=chatgpt.com" },
      { label: "Rajasthan 2022", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2022&utm_source=chatgpt.com" },
      { label: "Rajasthan Pavilion Tour", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2022+tour&utm_source=chatgpt.com" },
      { label: "Rajasthan 2021", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2021&utm_source=chatgpt.com" },
      { label: "Rajasthan Pavilion Tour", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2021+tour&utm_source=chatgpt.com" },
      { label: "Rajasthan 2020", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2020&utm_source=chatgpt.com" },
      { label: "Rajasthan 2019", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2019&utm_source=chatgpt.com" },
      { label: "Rajasthan EODB 2019", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2019+Ease+of+Doing+Business&utm_source=chatgpt.com" },
      { label: "Rajasthan 2018", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2018&utm_source=chatgpt.com" },
      { label: "Rajasthan Rural Enterprises", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2018+Rural+Enterprises&utm_source=chatgpt.com" },
      { label: "Rajasthan 2017", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2017&utm_source=chatgpt.com" },
      { label: "Rajasthan Mandap 2017", url: "https://www.youtube.com/results?search_query=Rajasthan+Mandap+IITF+2017&utm_source=chatgpt.com" },
      { label: "Rajasthan 2016", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2016&utm_source=chatgpt.com" },
      { label: "Rajasthan Mandap 2016", url: "https://www.youtube.com/results?search_query=Rajasthan+Mandap+IITF+2016&utm_source=chatgpt.com" },
      { label: "Rajasthan 2015", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2015&utm_source=chatgpt.com" },
      { label: "Rajasthan Crafts 2015", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2015+handicrafts&utm_source=chatgpt.com" },
      { label: "Rajasthan 2014", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2014&utm_source=chatgpt.com" },
      { label: "Rajasthan Mandap 2014", url: "https://www.youtube.com/results?search_query=Rajasthan+Mandap+IITF+2014&utm_source=chatgpt.com" },
      { label: "Rajasthan 2013", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+IITF+2013&utm_source=chatgpt.com" },
      { label: "Rajasthan Mandap 2013", url: "https://www.youtube.com/results?search_query=Rajasthan+Mandap+IITF+2013&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "Odisha Pavilion — 2025 to 2022",
    links: [
      { label: "Odisha 2025", url: "https://www.youtube.com/watch?v=xBZEdbxCcg8&utm_source=chatgpt.com" },
      { label: "Odisha 2025 Tour", url: "https://www.youtube.com/results?search_query=Odisha+Pavilion+IITF+2025+tour&utm_source=chatgpt.com" },
      { label: "Odisha Boita Dwara", url: "https://www.youtube.com/results?search_query=Odisha+Boita+Dwara+IITF+2025&utm_source=chatgpt.com" },
      { label: "Odisha Gold 2025", url: "https://www.youtube.com/results?search_query=Odisha+Pavilion+Gold+IITF+2025&utm_source=chatgpt.com" },
      { label: "Odisha 2024", url: "https://www.youtube.com/results?search_query=Odisha+Pavilion+IITF+2024&utm_source=chatgpt.com" },
      { label: "Odisha 2023", url: "https://www.youtube.com/watch?v=Cd0wqsZDCao&utm_source=chatgpt.com" },
      { label: "Odisha Mission Shakti", url: "https://www.youtube.com/watch?v=osoMcrpg4Gk&utm_source=chatgpt.com" },
      { label: "Odisha 2022", url: "https://www.youtube.com/watch?v=iEYSRzGvuMc&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "Madhya Pradesh Pavilion — 2025 to 2021",
    links: [
      { label: "MP 2025", url: "https://www.youtube.com/results?search_query=Madhya+Pradesh+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "MP 2024", url: "https://www.youtube.com/results?search_query=Madhya+Pradesh+Pavilion+IITF+2024&utm_source=chatgpt.com" },
      { label: "MP 2023", url: "https://www.youtube.com/results?search_query=Madhya+Pradesh+Pavilion+IITF+2023&utm_source=chatgpt.com" },
      { label: "MP Vocal Local", url: "https://www.youtube.com/results?search_query=MP+Pavilion+IITF+2022+Vocal+for+Local&utm_source=chatgpt.com" },
      { label: "MP 2021", url: "https://www.youtube.com/results?search_query=MP+Pavilion+IITF+2021+Atmanirbhar+MP&utm_source=chatgpt.com" },
      { label: "MP Shaurya Smarak", url: "https://www.youtube.com/results?search_query=MP+Shaurya+Smarak+IITF+Pavilion&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "Kerala Pavilion — 2025 to 2019",
    links: [
      { label: "Kerala 2025", url: "https://www.youtube.com/results?search_query=Kerala+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Kerala 2024", url: "https://www.youtube.com/results?search_query=Kerala+Pavilion+IITF+2024&utm_source=chatgpt.com" },
      { label: "Kerala 2023", url: "https://www.youtube.com/results?search_query=Kerala+Pavilion+IITF+2023&utm_source=chatgpt.com" },
      { label: "Kerala Tourism IITF", url: "https://www.youtube.com/results?search_query=Kerala+Tourism+IITF+Pavilion&utm_source=chatgpt.com" },
      { label: "Kerala 2019", url: "https://www.youtube.com/results?search_query=Kerala+Pavilion+IITF+2019&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "Award-Winning Pavilions — Recent Years",
    links: [
      { label: "Meghalaya Gold 2025", url: "https://www.youtube.com/results?search_query=Meghalaya+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Kerala Silver 2025", url: "https://www.youtube.com/results?search_query=Kerala+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Puducherry Bronze", url: "https://www.youtube.com/results?search_query=Puducherry+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Bihar Silver 2025", url: "https://www.youtube.com/watch?v=bAH2WHxbXFc&utm_source=chatgpt.com" },
      { label: "UP Bronze 2025", url: "https://www.youtube.com/results?search_query=UP+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Jharkhand Gold 2025", url: "https://www.youtube.com/results?search_query=Jharkhand+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "Defence Gold 2025", url: "https://www.youtube.com/results?search_query=Ministry+Defence+Pavilion+IITF+2025&utm_source=chatgpt.com" },
      { label: "CBIC Gold 2025", url: "https://www.youtube.com/watch?v=7wKF-gYDnFo&utm_source=chatgpt.com" },
      { label: "Bihar Gold 2024", url: "https://www.youtube.com/watch?v=bAH2WHxbXFc&utm_source=chatgpt.com" },
      { label: "Puducherry Gold 2024", url: "https://www.youtube.com/results?search_query=Puducherry+Pavilion+Gold+IITF+2024&utm_source=chatgpt.com" },
      { label: "MP Thematic Gold", url: "https://www.youtube.com/results?search_query=MP+Pavilion+Gold+IITF+2024+Thematic&utm_source=chatgpt.com" },
      { label: "Odisha Silver 2024", url: "https://www.youtube.com/results?search_query=Odisha+Pavilion+Silver+IITF+2024&utm_source=chatgpt.com" },
      { label: "Meghalaya Silver 2024", url: "https://www.youtube.com/results?search_query=Meghalaya+Pavilion+Silver+IITF+2024&utm_source=chatgpt.com" },
      { label: "Karnataka Bronze 2024", url: "https://www.youtube.com/results?search_query=Karnataka+Pavilion+Bronze+IITF+2024&utm_source=chatgpt.com" },
      { label: "Assam Bronze 2024", url: "https://www.youtube.com/results?search_query=Assam+Pavilion+Bronze+IITF+2024&utm_source=chatgpt.com" },
    ],
  },
  {
    heading: "Creative Pavilions — Other Events",
    links: [
      { label: "Aero India Pavilion", url: "https://www.youtube.com/watch?v=UiJseWnQoz4&utm_source=chatgpt.com" },
      { label: "Aero India Highlights", url: "https://www.youtube.com/watch?v=0ZaxzbjBs_g&utm_source=chatgpt.com" },
      { label: "AI Impact Pavilion", url: "https://www.youtube.com/results?search_query=India+AI+Impact+Expo+2026+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "Google AI Pavilion", url: "https://www.youtube.com/results?search_query=Google+Pavilion+AI+Impact+Summit+2026&utm_source=chatgpt.com" },
      { label: "HP Intel Pavilion", url: "https://www.youtube.com/results?search_query=HP+Intel+Pavilion+AI+Impact+Summit+2026&utm_source=chatgpt.com" },
      { label: "Bharat Tex 2025", url: "https://www.youtube.com/results?search_query=Bharat+Tex+2025+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "Bharat Tex Rajasthan", url: "https://www.youtube.com/results?search_query=Rajasthan+Pavilion+Bharat+Tex+2025&utm_source=chatgpt.com" },
      { label: "UP Trade Show", url: "https://www.youtube.com/results?search_query=UP+International+Trade+Show+2025+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "Gujarat Vibrant Summit", url: "https://www.youtube.com/results?search_query=Vibrant+Gujarat+2024+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "World Food India", url: "https://www.youtube.com/results?search_query=World+Food+India+2024+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "DefExpo Pavilion", url: "https://www.youtube.com/results?search_query=DefExpo+India+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "India Mobile Congress", url: "https://www.youtube.com/results?search_query=India+Mobile+Congress+2025+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "Surajkund Pavilions", url: "https://www.youtube.com/results?search_query=Surajkund+Mela+2025+pavilion+walkthrough&utm_source=chatgpt.com" },
      { label: "World Expo India", url: "https://www.youtube.com/results?search_query=India+pavilion+Expo+2020+Dubai+walkthrough&utm_source=chatgpt.com" },
    ],
  },
] as const;
